"""Outline export: Markdown and PDF (BL-23)."""
import re
import io

from app.models import Outline
from app.services.outline import SECTION_DISPLAY_NAMES, SECTION_ORDER


def _clean(text: str) -> str:
    """Normalise whitespace for export."""
    return text.strip()


def _draft_label(content: str) -> tuple[str, str]:
    """
    Split a section body into (bullets_block, draft_paragraph).
    The DRAFT: line may appear anywhere; everything before it is bullets.
    """
    parts = re.split(r'DRAFT:\s*', content, maxsplit=1, flags=re.IGNORECASE)
    bullets = parts[0].strip()
    draft = parts[1].strip() if len(parts) > 1 else ""
    return bullets, draft


# ── Markdown ──────────────────────────────────────────────────────────────────

def render_markdown(project_name: str, outline: Outline) -> str:
    date_str = outline.created_at.strftime("%B %d, %Y")
    style = outline.citation_style
    lines: list[str] = []

    lines += [
        f"<!-- DRAFT OUTLINE — AI-generated scaffold. Revise before submitting. -->",
        f"<!-- Generated by ScholarForge on {date_str} | Citation style: {style} -->",
        "",
    ]

    for key in SECTION_ORDER:
        sec = outline.sections.get(key, "").strip()
        if not sec:
            continue
        label = SECTION_DISPLAY_NAMES[key]

        if key == "title":
            lines += [f"# {sec}", ""]
            lines += [f"**Draft Outline — AI-generated scaffold. Revise before submitting.**  ", ""]
            continue

        lines += [f"## {label}", ""]

        if key in {"abstract", "index_terms", "references"}:
            lines += [sec, ""]
        else:
            bullets, draft = _draft_label(sec)
            if bullets:
                lines += [bullets, ""]
            if draft:
                lines += [f"> **Draft — revise before use:** {draft}", ""]

    return "\n".join(lines)


# ── PDF ───────────────────────────────────────────────────────────────────────

def _ascii_safe(text: str) -> str:
    """Replace common Unicode punctuation with ASCII equivalents for core PDF fonts."""
    replacements = {
        "—": "--", "–": "-", "‘": "'", "’": "'",
        "“": '"', "”": '"', "…": "...", " ": " ",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def render_pdf(project_name: str, outline: Outline) -> bytes:
    from fpdf import FPDF

    class _PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "I", 7.5)
            self.set_text_color(150, 150, 150)
            self.cell(0, 6, "DRAFT OUTLINE -- AI-generated scaffold. Revise before submitting. | ScholarForge", align="C")
            self.ln(2)
            self.set_text_color(0, 0, 0)

        def footer(self):
            self.set_y(-12)
            self.set_font("Helvetica", "I", 7.5)
            self.set_text_color(150, 150, 150)
            self.cell(0, 6, f"Page {self.page_no()}", align="C")
            self.set_text_color(0, 0, 0)

    pdf = _PDF()
    pdf.set_margins(22, 20, 22)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    date_str = outline.created_at.strftime("%B %d, %Y")

    # ── Title block ──
    usable_w = pdf.w - pdf.l_margin - pdf.r_margin
    title_text = _ascii_safe(outline.sections.get("title", project_name))
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(usable_w, 10, title_text, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(usable_w, 6, f"Citation style: {outline.citation_style}  |  Generated: {date_str}", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.set_draw_color(203, 213, 225)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)

    for key in SECTION_ORDER[1:]:  # skip title (already rendered above)
        sec = outline.sections.get(key, "").strip()
        if not sec:
            continue
        label = SECTION_DISPLAY_NAMES[key]

        # Section heading
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_x(pdf.l_margin)
        pdf.cell(usable_w, 8, label, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        if key in {"abstract", "index_terms", "references"}:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(usable_w, 5.5, _ascii_safe(sec))
        else:
            bullets, draft = _draft_label(sec)
            if bullets:
                pdf.set_font("Helvetica", "", 9.5)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(usable_w, 5.5, _ascii_safe(bullets))
            if draft:
                pdf.ln(2)
                draft_safe = _ascii_safe(draft)
                # coloured callout box
                x0, y0 = pdf.get_x(), pdf.get_y()
                pdf.set_fill_color(239, 246, 255)
                pdf.set_draw_color(191, 219, 254)
                # estimate height
                inner_w = usable_w - 6
                char_per_line = max(1, int(inner_w / 2.2))
                n_lines = max(1, len(draft_safe) // char_per_line + 1)
                box_h = n_lines * 5.5 + 12
                pdf.rect(x0, y0, usable_w, box_h, style="FD")
                pdf.set_xy(x0 + 3, y0 + 3)
                pdf.set_font("Helvetica", "B", 8.5)
                pdf.set_text_color(37, 99, 235)
                pdf.multi_cell(inner_w, 5.5, "Draft -- revise before use:")
                pdf.set_xy(x0 + 3, pdf.get_y())
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(55, 65, 81)
                pdf.multi_cell(inner_w, 5.5, draft_safe)
                pdf.set_text_color(0, 0, 0)
                # ensure cursor is below box
                if pdf.get_y() < y0 + box_h:
                    pdf.set_y(y0 + box_h)
        pdf.ln(5)

    return bytes(pdf.output())
